// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nunapqmqfyaujfdihwjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51bmFwcW1xZnlhdWpmZGlod2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDg3NDMsImV4cCI6MjA3MTgyNDc0M30.0StNZxk_sURwBpqlVND416BoTUSYdWjyyjpWuq_V99I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});